---
- name: Clone and Build kcp from source
  hosts: localhost
  become: true
  vars:
    source_repo: kcp-dev/kcp
    source_branch: main
  environment:
    IGNORE_GO_VERSION: 0
#
  tasks:
#
  - name: Ensure golang and make are installed
    ansible.builtin.package:
      name:
        - golang
        - make
      state: present

  - name: Clone {{ source_repo }}:{{ source_branch }} from github.com
    ansible.builtin.git:
      repo: https://github.com/{{ source_repo }}.git
      dest: src/{{ source_repo }}
      single_branch: yes
      version: "{{ source_branch }}"
      force: true      

  - name: Build
    community.general.make:
      chdir: src