---
- name: Clone and Build kcp from source
  hosts: localhost
  vars:
    # clone source
    source_repo: kcp-dev/kcp
    source_branch: main
    install: false
  environment:
    IGNORE_GO_VERSION: 1
#
  tasks:  
#
  - name: Clone {{ source_repo }}:{{ source_branch }} from github.com
    ansible.builtin.git:
      repo: https://github.com/{{ source_repo }}.git
      dest: src/{{ source_repo }}
      single_branch: yes
      version: "{{ source_branch }}"
      force: true

  - name: Build 
    community.general.make:
      chdir: src/{{ source_repo }}

  - name: Optionally Install KCP using built binaries
    import_playbook:
    vars:
      kcp_build_src: src/{{ source_repo }}/bin
    when: install | bool