---
- name: Install KCP
  hosts: localhost
  vars:
    kcp_secure_port: 6443
    kcp_extra_args: ""
    kcp_version: 0.10.0
    kcp_baseurl: https://github.com/kcp-dev/kcp/releases/download
    host_os: "{{ lookup('ansible.builtin.pipe', 'uname -s') | lower }}"
    host_arch: "{{ lookup('ansible.builtin.pipe', 'uname -m | sed s/aarch64/arm64/ | sed s/x86_64/amd64/') }}"
#
  tasks:
#
  - name: Download and extract kcp and kubectl plugin (v{{ kcp_version }}_{{ host_os }}_{{ host_arch }})
    ansible.builtin.unarchive:
      src: "{{ kcp_baseurl }}/v{{ kcp_version }}/{{ item }}_{{ kcp_version }}_{{ host_os }}_{{ host_arch }}.tar.gz"
      dest: /usr/local
      remote_src: yes
      setype: bin_t
    loop:
      - kcp
      - kubectl-kcp-plugin
    become: true

  - name: Install systemd unit
    ansible.builtin.copy:
      content: "{{ lookup('ansible.builtin.template', 'kcp.service.j2') }}"
      dest: /etc/systemd/system/kcp.service
      remote_src: yes
      force: true
    become: true

  - name: Enable and Start kcp systemd service on port {{ kcp_secure_port }}
    ansible.builtin.systemd:
      name: kcp
      state: restarted
      enabled: true
      daemon_reload: true
    become: true
