---
- name: Install kcp
  hosts: localhost
  vars:
    kcp_secure_port: 6443
    kcp_extra_args: ""
    kcp_version: 0.11.0
    kcp_rootdir: /etc/kcp
    kcp_kubeconfig_mode: 0644
    kcp_baseurl: https://github.com/kcp-dev/kcp/releases/download
    host_os: "{{ ansible_facts['system'] | lower }}"
    host_arch: "{{ ansible_facts['architecture'] | regex_replace('aarch64', 'arm64') | regex_replace('x86_64', 'amd64') }}"
  handlers:
    - name: Restart kcp
      ansible.builtin.systemd:
        name: kcp
        state: restarted
      become: true
#
  tasks:
#
  - name: Download and extract kcp and kubectl plugin (v{{ kcp_version }}_{{ host_os }}_{{ host_arch }})
    ansible.builtin.unarchive:
      src: "{{ kcp_baseurl }}/v{{ kcp_version }}/{{ item }}_{{ kcp_version }}_{{ host_os }}_{{ host_arch }}.tar.gz"
      dest: /usr/local
      remote_src: yes
      setype: bin_t
    loop:
      - kcp
      - kubectl-kcp-plugin
    become: true
    notify: Restart kcp

  - name: Install systemd unit
    ansible.builtin.template:
      src: kcp.service.j2
      dest: /etc/systemd/system/kcp.service
      mode: "0644"
    become: true
    notify: Restart kcp

  - name: Ensure root directory
    ansible.builtin.file:
      path: "{{ kcp_rootdir }}"
      state: directory
    become: true

  - name: Enable and Start kcp systemd service on port {{ kcp_secure_port }}
    ansible.builtin.systemd:
      name: kcp
      state: started
      enabled: true
      daemon_reload: true
    become: true
    notify: Restart kcp

  - name: Run this command to set kubeconfig readable without root
    debug:
      msg:
        - sudo chmod +r {{ kcp_rootdir }}/admin.kubeconfig

  - name: Run this command to access kcp
    debug:
      msg:
        - export KUBECONFIG={{ kcp_rootdir }}/admin.kubeconfig
